### ISSUE TITLE
Media field - uploaded image initially displays the wrong size

### ISSUE THREAD

**Issue by pdewouters** [alleyinteractive/wordpress-fieldmanager#367]
To duplicate this: select an image from a media field. . When you attach an image , the thumbnail in the admin interface shows it cropped and narrow, instead of its full width. When the post is saved (updated), then the image is displayed correctly on refresh.

![screen shot 2015-07-13 at 14 28 04](https://cloud.githubusercontent.com/assets/965789/8650550/65dca1be-296b-11e5-87c9-8afed5ff1474.png)

see screenshot

**Comment by danielbachhuber** [comment]
Uploaded images default to the proper thumbnail size for me:

![image](https://cloud.githubusercontent.com/assets/36432/13178257/a688bcd8-d6d2-11e5-89cb-7f35b9f6c749.png)

@pdewouters Do you still have access to the environment this issue originally manifested in? Can you see if it reproduces after #409 ?

**Comment by danielbachhuber** [comment]
To see if I could replicate the problem of #409, I was also unable to reproduce at f20bb90 using a repeatable image group:

![image](https://cloud.githubusercontent.com/assets/36432/13178383/7f1ef9ea-d6d3-11e5-93b8-252fcb645f14.png)

Here's the field definition I used:

```
add_action( 'fm_post_post', function(){
	$group = new Fieldmanager_Group( 'Image Group', array(
		'name' => 'image-group',
		'limit' => 0,
	) );
	$media = new Fieldmanager_Media( 'image', array(
		'name'     => 'image',
	) );
	$group->add_child( $media );
	$group->add_meta_box( 'Image', array( 'post' ) );
});
```

**Comment by dlh01** [comment]
Possibly fixed after #388?

**Comment by mboynes** [comment]
Almost certainly was fixed after #388. Closing.

**Comment by pdewouters** [comment]
Sorry, I missed those pings. I'm currently on a different project and this issue is still present
