### ISSUE TITLE
Wordpress 5.0 issue

### ISSUE THREAD

**Issue by Sitetools** [alleyinteractive/wordpress-fieldmanager#730]
When upgrading WordPress to 5.0 Autocomplete is breaking, below is what I'm using.
There are no suggested pages displaying as I add chars to the form field.
I can't see any JavaScript or xhr errors in the console.

'link' => new Fieldmanager_Autocomplete(
                            'Button link, start typing page title', 
                            array('datasource' => new Fieldmanager_Datasource_Post())
                        ),

**Comment by dlh01** [comment]
@Sitetools Could you test whether this is the same issue as #710 and is therefore fixed by #717?

**Comment by pbearne** [comment]
I installed #717 and this didn't fix it all the select2 controls as not loading

**Comment by kevinfodness** [comment]
Fixed via #757
